name: Set up uv
description: Install uv and Python and, if desired, dependencies
inputs:
  install-and-cache-dependencies:
    default: "false"
    description: whether to install the dependencies specified in pyproject.toml
    required: true
  python-version:
    description: Python version to be installed
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        enable-cache: ${{ fromJSON(inputs.install-and-cache-dependencies) }}
        python-version: ${{ inputs.python-version }}
    - if: fromJSON(inputs.install-and-cache-dependencies)
      run: uv sync --all-extras --locked
      shell: bash
