name: CI

on:
  - push

permissions: { }

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@6f912829b4e872ce326aea1cdb09f7894b84a2ca # 2026.9.18
      - run: uv build --verbose
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@6f912829b4e872ce326aea1cdb09f7894b84a2ca # 2026.9.18
        with:
          install-and-cache-dependencies: true
      - uses: christophgietl/uv-actions/set-up-pre-commit@6f912829b4e872ce326aea1cdb09f7894b84a2ca # 2026.9.18
        with:
          cache-key-suffix: lint-and-test
      - run: uv run --no-sync pre-commit run --all-files --show-diff-on-failure
      - env:
          PYTHONIOENCODING: utf-8 # avoids UnicodeEncodeError in Windows (see https://github.com/Textualize/rich/issues/2411)
        run: uv run --no-sync import-linter lint
      - run: uv run --no-sync pyright
      - run: uv run --no-sync pytest
