name: CI

on:
  - push

permissions: { }

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@d231379b0f63cd19bc39d7e5b4d5057a2daffc17 # 2026.8.24
        with:
          install-and-cache-dependencies: true
      - uses: christophgietl/uv-actions/set-up-pre-commit@d231379b0f63cd19bc39d7e5b4d5057a2daffc17 # 2026.8.24
        with:
          cache-key-suffix: lint-and-test
      - run: uv run --no-sync pre-commit run --all-files --show-diff-on-failure
      - env:
          PYTHONIOENCODING: utf-8 # avoids UnicodeEncodeError in Windows (see https://github.com/Textualize/rich/issues/2411)
        run: uv run --no-sync import-linter lint
      - run: uv run --no-sync pyright
      - run: uv run --no-sync pytest
