name: CI

on:
  - push

permissions: { }

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@f025ee6ab6bc5d0cdf1390f59ca7506564598141 # 2026.4.25
        with:
          install-and-cache-dependencies: true
      - uses: christophgietl/uv-actions/set-up-pre-commit@f025ee6ab6bc5d0cdf1390f59ca7506564598141 # 2026.4.25
        with:
          cache-key-suffix: lint-and-test
      - run: uv run --no-sync pre-commit run --all-files --show-diff-on-failure
      - env:
          PYTHONIOENCODING: utf-8 # avoids UnicodeEncodeError in Windows (see https://github.com/Textualize/rich/issues/2411)
        run: uv run --no-sync lint-imports
      - run: uv run --no-sync pyright
      - run: uv run --no-sync pytest
