name: Copilot setup steps

on:
  # Automatically trigger the workflow on modification for testing purposes:
  pull_request:
    paths:
      - .github/actions/set-up-pre-commit/action.yml
      - .github/actions/set-up-uv/action.yml
      - .github/workflows/copilot-setup-steps.yml
  push:
    paths:
      - .github/actions/set-up-pre-commit/action.yml
      - .github/actions/set-up-uv/action.yml
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

permissions: { }

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/set-up-uv
        with:
          install-and-cache-dependencies: true
      - uses: ./.github/actions/set-up-pre-commit
        with:
          cache-key-suffix: copilot-setup-steps
          install-git-hooks: true
