name: Copilot setup steps

on:
  # Automatically trigger the workflow on modification for testing purposes:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

permissions: { }

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv-and-pre-commit-for-copilot@d231379b0f63cd19bc39d7e5b4d5057a2daffc17 # 2026.8.24
